version: '3.7'

services:
  agent:
    command:
      - -log-level
      - debug
    env_file: .env
    image: defn/vault-agent:1.6.3
    volumes:
      - ./etc/vault:/vault
    ports:
      - 8200:8200
